apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  tasks:
  - name: test-syft-oci-dir
    taskRef:
      name: test-syft-oci-dir
  - name: test-syft-overlay-dir
    taskRef:
      name: test-syft-overlay-dir
  - name: test-syft-oci-dir-2gi
    taskRef:
      name: test-syft-oci-dir-2gi
  - name: test-syft-overlay-dir-2gi
    taskRef:
      name: test-syft-overlay-dir-2gi
